### PR TITLE
Update googleseo.lang.php

### PR DESCRIPTION
**Pull request by borekon**
Use https instead of http

### CODE REVIEW

**Comment by frostschutz** [comment]
Great catch, thank you!

**Comment by frostschutz** [comment]
@borekon Does it still work for you properly, though?

The Google documentation this was originally based on ( https://webmasters.googleblog.com/2008/08/make-your-404-pages-more-useful.html ) claims that "The described product or service is no longer available."

You can see in the screenshots there it's supposed to show a "closest match" and other suggestions and the search box at the bottom.

Now it only ever seems to give me the search box and nothing else...

**Comment by borekon** [comment]
I not tried it. I was only searching console errors on my site. Anyway, the link with https heads me to the javascript file.
________________________________
De: Andreas Klauer <notifications@github.com>
Enviado: sábado, 13 de julio de 2019 18:33
Para: frostschutz/MyBB-Google-SEO
Cc: Alfonso; Mention
Asunto: Re: [frostschutz/MyBB-Google-SEO] Update googleseo.lang.php (#69)


@borekon<https://github.com/borekon> Does it still work for you properly, though?

The Google documentation this was originally based on ( https://webmasters.googleblog.com/2008/08/make-your-404-pages-more-useful.html ) claims that "The described product or service is no longer available."

You can see in the screenshots there it's supposed to show a "closest match" and other suggestions and the search box at the bottom.

Now it only ever seems to give me the search box and nothing else...

**Comment by frostschutz** [comment]
@borekon Thanks, opened a new issue #70

**Pull request merged**
